### PR TITLE
Persist category selections made via Legend Superpowers

### PR DESCRIPTION
**Pull request by barryhughes**
If Legend Superpowers are enabled, and a visitor selects a category then navigates to the next month, their selection is 'lost'. This change makes it so that the category selection persists.

Inspired by: [wordpress.org/support/topic/when-changing-the-month-preselected-category-is-not-retained](https://wordpress.org/support/topic/when-changing-the-month-preselected-category-is-not-retained/)

---

teccc-category-persistance

The idea is that:

- If a category is selected, and the user navigates to the next month, then we retain that selection.
- If they clear the selection (ie, no categories are selected), then navigate to another month, the selection stays cleared.
- If they select a category, then navigate to another month where that category is not present on the page, the selection is implicitly dropped.

I saw this idea in the linked forum post and thought I'd throw something together:

- I'm a little unsure if this should be behind some kind of setting, like *"Persist Superpower Selections"* (assuming it should be included at all, that is).
- It does require some more testing (particularly in relation to views besides month view), but I wanted to submit the PR early, for your initial feedback, first of all.

### CODE REVIEW

**Comment by afragen** [comment]
Hey Barry! Great to hear from you!

Give me some time to review and test, but this is great and I think it should just be the default behavior.

**Comment by barryhughes** [comment]
Yes, been a while! Sure thing—will keep a watch for any feedback 👍🏼

**Comment by afragen** [comment]
I'm gonna let you resolve the merge conflicts here. I did add WPCS for the JS files so you might need to pull `develop` again.

**Comment by barryhughes** [comment]
Thanks, Andy!

- Rebased, so it is up-to-date with the latest `develop` branch code.
- Resolved conflicts following merge of https://github.com/afragen/the-events-calendar-category-colors/pull/145.
- Following your note re WPCS [(this commit?)](https://github.com/afragen/the-events-calendar-category-colors/commit/7478bf6164716e09c88d4cdd6c9e76586151d021) I did run PHPCS and got some errors relating to lines changed in this PR, but they generally *seemed* like they might be ones I should ignore (such as PEAR rules that normally apply to PHP rather than JS ... but it's also very possible I invoked PHPCS incorrectly). Anyway, happy to revisit and get it right if I mis-stepped :+1:

**Comment by afragen** [comment]
I'll try to add the PHPCS into the project via composer if I haven't already.

**Pull request merged**
